# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
                ('redact_date', models.DateTimeField(verbose_name='last modified date')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('is_logged', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reserv',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Room'),
        ),
        migrations.AddField(
            model_name='reserv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User'),
        ),
    ]
